version: '3.3'
services:
  postgres_db:
    image: postgres:latest
    container_name: pg-springdb
    restart: always
    environment:
      POSTGRES_DB: "springdb"
      POSTGRES_USER: "apti"
      POSTGRES_PASSWORD: "apti959595"
    ports:
      - "54321:5432"
    volumes:
      - db_data:/var/lib/postgresql/springdb/data
volumes:
  db_data:
